use gpui::actions;

actions!(
    mini_pi,
    [
        CloseWindow,
        Quit,
        SendMessage,
        Login,
        Logout,
        SignUp,
        ConfirmInlineEdit,
        CancelInlineEdit,
        StopStreaming,
        ShowMainWindow,
        ToggleMainWindow,
        CreateThread,
        About,
        OpenInstallExtensionWindow,
        OpenPiSettingsWindow,
        SelectFontSmall,
        SelectFontMedium,
        SelectFontLarge,
        Copy,
        Cut,
        Paste,
        SelectAll,
        Undo,
        Redo,
    ]
);
